name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: G-Research/github-terraformer/.github/workflows/bulk-import.yaml@add-support-for-custom-properties
    with:
      gcss_ref: add-support-for-custom-properties
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}