name: "Drift Check"

on:
#  schedule:
#    - cron: '*/15 * * * *'
 workflow_dispatch:

jobs:
  drift-check:
    secrets:
      tfc_token: ${{ secrets.TFC_TOKEN }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
    uses: G-Research/github-terraformer/.github/workflows/drift-check.yaml@test/rc-cycle
    with:
      gcss_ref: test/rc-cycle
      tfc_org: "GR-OSS"
      reviewers: ${{ vars.DRIFT_REVIEWERS }}