name: "Drift Check"

on:
#  schedule:
#    - cron: '*/15 * * * *'
 workflow_dispatch:

jobs:
  drift-check:
    secrets:
      tfc_token: ${{ secrets.TFC_TOKEN }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
    uses: G-Research/github-terraformer/.github/workflows/drift-check.yaml@non-main-default-branch-via-branches
    with:
      gcss_ref: non-main-default-branch-via-branches
      tfc_org: "GR-OSS"
