name: Import organisation

on:
  workflow_dispatch:

jobs:
  import-org:
    uses: G-Research/github-terraformer/.github/workflows/import-org.yaml@v0.3.0-rc.2
    with:
      gcss_ref: v0.3.0-rc.2
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
