name: Import organisation

on:
  workflow_dispatch:

jobs:
  import-org:
    uses: G-Research/github-terraformer/.github/workflows/import-org.yaml@non-main-default-branch-via-branches
    with:
      gcss_ref: non-main-default-branch-via-branches
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
